[build-system]
requires = ["setuptools>=83.0.0", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "pyani"
dynamic = ["version"]
requires-python = ">=3.10"
dependencies = [
    "gql==4.0.0",
    "httpx==0.28.1",
    "pyside6-essentials==6.11.1",
    "ladybug"
]

[tool.pyside6-project]
files = ["src/mainwindow.py"]

[tool.setuptools_scm]
